<?php

namespace Database\Seeders;

use App\Models\BirthRecord;
use App\Models\Doctor;
use App\Models\User;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class BirthRecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = Doctor::all();
        $bidan = User::role('bidan')->first() ?? User::first();

        if ($doctors->isEmpty()) {
            $this->command->error('No doctors found. Please run DoctorSeeder first.');
            return;
        }

        $birthRecords = [
            [
                'baby_name' => 'Baby Ahmad Fauzan',
                'birth_date' => Carbon::now()->subDays(30),
                'birth_time' => '08:30:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0001',
                'gender' => 'Laki-laki',
                'child_order' => 1,
                'delivery_method' => 'Normal',
                'baby_blood_type' => 'A',
                'weight' => 3200,
                'length' => 50,
                'head_circ' => 34,
                'chest_circ' => 33,
                'mother_name' => 'Siti Aminah',
                'mother_medical_record_no' => 'RM-IBU-2026-0001',
                'mother_ktp' => '3201234567890001',
                'mother_address' => 'Jl. Melati No. 15, Kec. Cibadak, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'mother_blood_type' => 'A',
                'father_name' => 'Ahmad Hidayat',
                'father_ktp' => '3201234567890002',
                'father_address' => 'Jl. Melati No. 15, Kec. Cibadak, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'Wiraswasta',
                'father_blood_type' => 'O',
            ],
            [
                'baby_name' => 'Baby Putri Ayu Lestari',
                'birth_date' => Carbon::now()->subDays(25),
                'birth_time' => '14:15:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0002',
                'gender' => 'Perempuan',
                'child_order' => 2,
                'delivery_method' => 'Caesar',
                'baby_blood_type' => 'B',
                'weight' => 2800,
                'length' => 48,
                'head_circ' => 33,
                'chest_circ' => 32,
                'mother_name' => 'Dewi Kartika',
                'mother_medical_record_no' => 'RM-IBU-2026-0002',
                'mother_ktp' => '3201234567890003',
                'mother_address' => 'Jl. Mawar No. 22, Kec. Cisaat, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Guru',
                'mother_blood_type' => 'B',
                'father_name' => 'Budi Setiawan',
                'father_ktp' => '3201234567890004',
                'father_address' => 'Jl. Mawar No. 22, Kec. Cisaat, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'PNS',
                'father_blood_type' => 'AB',
            ],
            [
                'baby_name' => 'Baby Muhammad Rizky',
                'birth_date' => Carbon::now()->subDays(20),
                'birth_time' => '22:45:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0003',
                'gender' => 'Laki-laki',
                'child_order' => 1,
                'delivery_method' => 'Normal',
                'baby_blood_type' => 'O',
                'weight' => 3500,
                'length' => 52,
                'head_circ' => 35,
                'chest_circ' => 34,
                'mother_name' => 'Ratna Sari',
                'mother_medical_record_no' => 'RM-IBU-2026-0003',
                'mother_ktp' => '3201234567890005',
                'mother_address' => 'Jl. Anggrek No. 8, Kec. Sukaraja, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Dokter',
                'mother_blood_type' => 'O',
                'father_name' => 'Rizky Pratama',
                'father_ktp' => '3201234567890006',
                'father_address' => 'Jl. Anggrek No. 8, Kec. Sukaraja, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'Pengacara',
                'father_blood_type' => 'O',
            ],
            [
                'baby_name' => 'Baby Aisyah Zahra',
                'birth_date' => Carbon::now()->subDays(15),
                'birth_time' => '03:20:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0004',
                'gender' => 'Perempuan',
                'child_order' => 3,
                'delivery_method' => 'Normal',
                'baby_blood_type' => 'AB',
                'weight' => 3100,
                'length' => 49,
                'head_circ' => 34,
                'chest_circ' => 33,
                'mother_name' => 'Nur Hidayah',
                'mother_medical_record_no' => 'RM-IBU-2026-0004',
                'mother_ktp' => '3201234567890007',
                'mother_address' => 'Jl. Kenanga No. 5, Kec. Cikembar, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Perawat',
                'mother_blood_type' => 'A',
                'father_name' => 'Farhan Abdullah',
                'father_ktp' => '3201234567890008',
                'father_address' => 'Jl. Kenanga No. 5, Kec. Cikembar, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'TNI',
                'father_blood_type' => 'B',
            ],
            [
                'baby_name' => 'Baby Kenji Pratama',
                'birth_date' => Carbon::now()->subDays(10),
                'birth_time' => '11:00:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0005',
                'gender' => 'Laki-laki',
                'child_order' => 1,
                'delivery_method' => 'Caesar',
                'baby_blood_type' => 'A',
                'weight' => 3400,
                'length' => 51,
                'head_circ' => 35,
                'chest_circ' => 34,
                'mother_name' => 'Yuki Tanaka',
                'mother_medical_record_no' => 'RM-IBU-2026-0005',
                'mother_ktp' => '3201234567890009',
                'mother_address' => 'Jl. Dahlia No. 12, Kec. Palabuhanratu, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Pengusaha',
                'mother_blood_type' => 'A',
                'father_name' => 'Dimas Pratama',
                'father_ktp' => '3201234567890010',
                'father_address' => 'Jl. Dahlia No. 12, Kec. Palabuhanratu, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'Nelayan',
                'father_blood_type' => 'A',
            ],
            [
                'baby_name' => 'Baby Naila Safira',
                'birth_date' => Carbon::now()->subDays(5),
                'birth_time' => '16:30:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0006',
                'gender' => 'Perempuan',
                'child_order' => 2,
                'delivery_method' => 'Normal',
                'baby_blood_type' => 'B',
                'weight' => 2900,
                'length' => 47,
                'head_circ' => 33,
                'chest_circ' => 32,
                'mother_name' => 'Maya Sari',
                'mother_medical_record_no' => 'RM-IBU-2026-0006',
                'mother_ktp' => '3201234567890011',
                'mother_address' => 'Jl. Flamboyan No. 3, Kec. Cicurug, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Apoteker',
                'mother_blood_type' => 'O',
                'father_name' => 'Agus Wijaya',
                'father_ktp' => '3201234567890012',
                'father_address' => 'Jl. Flamboyan No. 3, Kec. Cicurug, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'Polisi',
                'father_blood_type' => 'B',
            ],
            [
                'baby_name' => 'Baby Arjuna Putra',
                'birth_date' => Carbon::now()->subDays(3),
                'birth_time' => '09:15:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0007',
                'gender' => 'Laki-laki',
                'child_order' => 1,
                'delivery_method' => 'Normal',
                'baby_blood_type' => 'O',
                'weight' => 3600,
                'length' => 53,
                'head_circ' => 36,
                'chest_circ' => 35,
                'mother_name' => 'Indah Permata',
                'mother_medical_record_no' => 'RM-IBU-2026-0007',
                'mother_ktp' => '3201234567890013',
                'mother_address' => 'Jl. Teratai No. 7, Kec. Parung Kuda, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Bidan',
                'mother_blood_type' => 'O',
                'father_name' => 'Andi Kurniawan',
                'father_ktp' => '3201234567890014',
                'father_address' => 'Jl. Teratai No. 7, Kec. Parung Kuda, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'Pilot',
                'father_blood_type' => 'A',
            ],
            [
                'baby_name' => 'Baby Cantika Maharani',
                'birth_date' => Carbon::now()->subDays(1),
                'birth_time' => '19:45:00',
                'hospital_name' => 'RS Unggul Karsa Medika',
                'medical_record_no' => 'RM-2026-0008',
                'gender' => 'Perempuan',
                'child_order' => 1,
                'delivery_method' => 'Caesar',
                'baby_blood_type' => 'AB',
                'weight' => 2700,
                'length' => 46,
                'head_circ' => 32,
                'chest_circ' => 31,
                'mother_name' => 'Rani Maharani',
                'mother_medical_record_no' => 'RM-IBU-2026-0008',
                'mother_ktp' => '3201234567890015',
                'mother_address' => 'Jl. Bougenville No. 18, Kec. Cibitung, Kab. Sukabumi, Jawa Barat',
                'mother_occupation' => 'Akuntan',
                'mother_blood_type' => 'A',
                'father_name' => 'Hendra Gunawan',
                'father_ktp' => '3201234567890016',
                'father_address' => 'Jl. Bougenville No. 18, Kec. Cibitung, Kab. Sukabumi, Jawa Barat',
                'father_occupation' => 'Arsitek',
                'father_blood_type' => 'B',
            ],
        ];

        foreach ($birthRecords as $index => $record) {
            $record['doctor_id'] = $doctors->random()->id;
            $record['created_by_user_id'] = $bidan?->id;
            
            BirthRecord::firstOrCreate(
                ['medical_record_no' => $record['medical_record_no']],
                $record
            );
        }

        $this->command->info('Birth Records seeded successfully! Total: ' . count($birthRecords) . ' records');
    }
}
